#!/bin/csh -f

if ( "x$1" == "x" ) then
  # XXX Assumes the router has DHCP running AND probably that you are on Paul's mac
  set ip=`ifconfig en0 | grep "inet " | awk '{ print $2;}' | cut -f1-3 -d.`.1
else
  set ip=$1
endif

# Try logging in with telnet and setting root password if not already done.
libexec/telnet_set_root_pass ${ip}

set model=`ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -o TCPKeepAlive=yes -o ServerAliveInterval=5  root@${ip} "( . /lib/ar71xx.sh  ; ar71xx_board_name )"`
echo "Upgrading OpenWRT on the $model at $ip"

if ( "x$2" != "x" ) then
   set model=$2
endif

scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  openwrt-ar71xx-generic-${model}-v1-squashfs-factory.bin root@${ip}:/tmp
# We use a short keep-alive interval so that ssh realises when the far end has rebooted and dropped the connection.
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -o TCPKeepAlive=yes -o ServerAliveInterval=5  root@${ip} "( cd /tmp ; sysupgrade -v openwrt-ar71xx-generic-${model}-v1-squashfs-factory.bin )"
