#!/bin/csh -f

set path=($path ~/g/serval-dna)

cd instance
setenv SERVALINSTANCE_PATH `pwd`
cd ..

servald stop
rm servald-instance/rhizome.db
servald start

echo "My SID is "`servald id self | tail -1`

# Now create OTA update file

# Start by including the files to be updated (currently just
# the main binaries, we can add more stuff later)
( cd ../staging/ ; tar zcvf - servald lbard  ) > files.tgz
cat ota-shell >ota-complete
cat files.tgz >> ota-complete

servald rhizome add file --force-new `servald id self |tail -1` ota-complete me-ota-update.manifest "#arkaroolai2015" > bootstrap.log

servald rhizome list

set bundleid=`grep manifestid bootstrap.log | cut -f2 -d:`
set bk=`grep BK bootstrap.log | cut -f2 -d:`
echo "BID = $bundleid, BK = $bk"

# Create bundleid file for OTA update
echo $bundleid > ../image-files/etc/serval/ota-bundleid.txt


