#!/bin/csh -fx

set path=($path ~/g/serval-dna)

cd instance
setenv SERVALINSTANCE_PATH `pwd`
cd ..

servald stop
rm servald-instance/rhizome.db
servald start

echo "My SID is "`servald id self | tail -1`

# Now create OTA update file

# Start by including the files to be updated (currently just
# the main binaries, we can add more stuff later)
( cd ../staging/ ; tar zcvf - servald lbard  ) > files.tgz
cat ota-shell >ota-complete
cat files.tgz >> ota-complete

if ( -e me-ota-update.manifest ) then
  rm me-ota-update.manifest
endif

servald rhizome list

servald rhizome add file --force-new `servald id self |tail -1` ota-complete me-ota-update.manifest "#arkaroolai2015" 

servald rhizome list

set bundleid=`servald rhizome list | tail -1 | cut -f3 -d:`
echo "BID = $bundleid"

# Create bundleid file for OTA update
echo $bundleid > ../image-files/etc/serval/ota-bundleid.txt


