#!/bin/csh -fx

./stop-broadcast

set path=($path ~/g/serval-dna)

cd syncinst
setenv SERVALINSTANCE_PATH `pwd`
cd ..

servald stop
rm syncinst/rhizome.db
rm syncinst/serval.keyring
servald start

servald rhizome import bundle ota-complete me-ota-update.manifest 

servald rhizome list

sleep 5

servald id peers
