#!/bin/sh

cd /serval
rm -fr ota-update
rmdir ota-update
mkdir ota-update
cd ota-update

# Extract tar file from the end of this script.
dd if=$0 of=files.tgz bs=8192 skip=1
tar zxvf files.tgz

# Copy files into place
# (move running binaries out of the way first)

mv /serval/servald /serval/servald.ota-old
mv servald /serval/servald

mv /serval/flash900 /serval/flash900.ota-old
mv flash900 /serval/flash900

mv /serval/lbard /serval/lbard.ota-old
mv lbard /serval/lbard

mv /etc/serval/runlbard /etc/serval/runlbard.ota-old
mv runlbard /etc/serval/runlbard

mv rfd900* /serval/

# Stop runlbard so that we can start it again with our new version.
thepid=` ps | grep runlbard | grep -v grep | cut -c1-6`
kill $thepid
/etc/serval/runlbard &
lbardpid=` ps | grep /serval/lbard | grep -v grep | cut -c1-6`
kill $lbardpid

# stop servald to allow them to respawn with the new version
/serval/servald stop

# Give servald time to restart
sleep 10

# Now send a MeshMS to whoever cares about this mesh extender
if [ -e /dos/monitor.sid ]; then
  RECIPIENT=`cat /dos/monitor.sid`
  COMMIT="GITCOMMITSTUFF"
  /serval/servald meshms send message `/serval/servald keyring list | tail -1 | cut -f1 -d:` ${RECIPIENT} "Over-the-air-update installed on this mesh extender: git ${COMMIT}"
fi

# Exit explicitly, because we are following on with a tar ball
exit 0

# EOF
