#!/bin/sh

cd /serval
rm -fr ota-update
rmdir ota-update
mkdir ota-update
cd ota-update

# Extract tar file from the end of this script.
dd if=$0 of=files.tgz bs=8192 skip=1
tar zxvf files.tgz

# Copy files into place
# (move running binaries out of the way first)

mv /serval/servald /serval/servald.ota-old
mv servald /serval/servald

mv /serval/flash900 /serval/flash900.ota-old
mv flash900 /serval/flash900

mv /serval/lbard /serval/lbard.ota-old
mv lbard /serval/lbard

mv /etc/serval/runlbard /etc/serval/runlbard.ota-old
mv runlbard /etc/serval/runlbard

mv rfd900* /serval/

# stop servald and lbard to allow them to respawn with 
# the new version
/serval/servald stop
lbardpid=` ps | grep /serval/lbard | grep -v grep | cut -c1-6`
kill $lbardpid

# Exit explicitly, because we are following on with a tar ball
exit 0

# EOF
