#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=47

start() {
  if [ ! -e /dev/sda1 ]; then
    # No USB present -- this is usually caused by a known hardware bug
    # in the Atheros 9k USB host controller. It can only be fixed by 
    # physically removing power -- a soft reset doesn't work.
    # To at least alert the user that this is happening, we will
    # blink the LEDs in a distinctive pattern.

    # remove normal triggers to update leds
    for i in /sys/class/leds/* ; do echo none > "$i"/trigger ; done

    # Toggle LEDs continuously
    while true; do
      echo 0 > /sys/class/leds/tp-link:green:3g/brightness
      echo 0 > /sys/class/leds/tp-link:green:lan/brightness
      echo 255 > /sys/class/leds/tp-link:green:wlan/brightness
      echo 255 > /sys/class/leds/tp-link:green:wps/brightness
      sleep 0.3
      echo 255 > /sys/class/leds/tp-link:green:3g/brightness
      echo 255 > /sys/class/leds/tp-link:green:lan/brightness
      echo 0 > /sys/class/leds/tp-link:green:wlan/brightness
      echo 0 > /sys/class/leds/tp-link:green:wps/brightness
      sleep 0.3
    done
  fi
  e2fsck -a
  dosfsck /dev/sda1
  mount -a
}

stop() {
}
