#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=47

start() {

  usbgpiod=0

  if [ ! -e /dev/sda1 ]; then
    # No device, so try powering down the USB port, and powering it back up
    # to get it right.
    echo 0 > /sys/class/gpio/gpio8/value
    sleep 2
    echo 1 > /sys/class/gpio/gpio8/value
    sleep 2
    usbgpiod=1
  fi

  e2fsck -a
  dosfsck /dev/sda1
  mount -a
  if [ -e /dev/sda1 ] && [ -e /dos/MeshExtender]; then
    # on first boot, the partitions are mounted under /tmp instead of in
    # the right place, so reboot
    reboot
  fi
  # If that wasn't the problem, and there is no device, or it hasn't mounted,
  # then we have a bigger problem ...
  if [ ! -e /dev/sda1 ] || [ -e /serval/MeshExtender ] || [ -e /serval-var/MeshExtender]; then
    # No USB present, or failed to mount -- this is usually caused by a known hardware bug
    # in the Atheros 9k USB host controller. It can only be fixed by 
    # physically removing power -- a soft reset doesn't work.
    # To at least alert the user that this is happening, we will
    # blink the LEDs in a distinctive pattern.
  
    # remove normal triggers to update leds
    for i in /sys/class/leds/* ; do echo none > "$i"/trigger ; done

    # Toggle LEDs continuously
    while true; do
      echo 0 > /sys/class/leds/tp-link:green:3g/brightness
      echo 0 > /sys/class/leds/tp-link:green:lan/brightness
      echo 255 > /sys/class/leds/tp-link:green:wlan/brightness
      echo 255 > /sys/class/leds/tp-link:green:wps/brightness
      lua -e 'require("socket"); socket.sleep(0.2);'
      echo 255 > /sys/class/leds/tp-link:green:3g/brightness
      echo 255 > /sys/class/leds/tp-link:green:lan/brightness
      echo 0 > /sys/class/leds/tp-link:green:wlan/brightness
      echo 0 > /sys/class/leds/tp-link:green:wps/brightness
      lua -e 'require("socket"); socket.sleep(0.2);'
    done
  fi 
 
  # Keep track of whether we had to jump-start the USB port or not.
  echo $usbgpiod >> /serval-var/usbgpiohistory
}

