#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=49

start() {
  # Clear out old inittab incase it tries to include ttyATH0
  # atleast that way a reboot will get things working.
  rm /overlay/etc/inittab

  # Start servald
  mount /serval
  /serval/sbin/e2fsck -a
  mount -a
  export SERVALINSTANCE_PATH=/etc/serval
  mkdir -p $SERVALINSTANCE_PATH
  /etc/serval/runservald &
}

stop() {
  export SERVALINSTANCE_PATH=/etc/serval
  /serval/servald stop
}
