#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=49

start() {
  # Clear out old inittab incase it tries to include ttyATH0
  # atleast that way a reboot will get things working.
  if [ -e /overlay/etc/inittab ]; then
    rm /overlay/etc/inittab
    reboot
  fi

  # Flash radio if required
  /mesh-extender/flash900 /mesh-extender/radio~rfd900a.ihx /dev/ttyATH0 >/dev/null 2>&1

  # Start servald
  export SERVALINSTANCE_PATH=/etc/serval
  mkdir -p $SERVALINSTANCE_PATH

  mount -a

  /etc/serval/runservald &
}

stop() {
  export SERVALINSTANCE_PATH=/etc/serval
  /serval/servald stop
}
