#!/bin/sh

#
# Watch for over-the-air updates, and execute them if available
#
#
bundleid=`cat /dos/otabid.txt`

# Allow 10 seconds for servald to start up
sleep 10

while [ 1 ]
do

currentversion=`cat /serval/www/ota-update-version.html`
if [ -z $currentversion ]; then
  currentversion=0
fi
echo "Bundleid = '$bundleid'"

rhizomeversion=`/serval/servald rhizome list | grep -i ${bundleid} | cut -f4 -d:`
if [ ! -z "$rhizomeversion" ]; then
  if [ $rhizomeversion -gt $currentversion ]; then
    # We have found a newer version
    rm /dos/ota-update
    /serval/servald rhizome extract file ${bundleid} /dos/ota-update
    if [ -e /dos/ota-update ]; then
      chmod 755 /dos/ota-update
      /dos/ota-update && echo "$rhizomeversion" > /serval/www/ota-update-version.html
      # Create some nice diagnostic files so that we can work out what version of
      # binaries we are using.
      ls -l /serval > /serval/www/ota-update-result.html
      servald help > /serval/www/servald.txt
      strings /serval/lbard > /serval/www/lbard.txt 
    fi
  fi
fi


sleep 10
done
