#!/bin/sh

#
# run lbard, and restart if it terminates for any reason
# (it is experimental software, after all).
#
while [ 1 ]
do
/serval/lbard 127.0.0.1:4110 lbard:lbard `/serval/servald id self | tail -1` /dev/ttyATH0 
sleep 3
done
