#!/bin/sh

#
# run lbard, and restart if it terminates for any reason
# (it is experimental software, after all).
#

# Allow 10 seconds for servald to start up so that we can read our SID
sleep 10

while [ 1 ]
do
/serval/lbard 127.0.0.1:4110 lbard:lbard `/serval/servald id self | tail -1` /dev/ttyATH0 
servald stop
sleep 3
done
