#!/bin/sh -x >/tmp/b.log

# servald for MIPS mesh extender bundleid
bundleid=D1057555117D5411AEC058DE8A38FA780F2886224588B67B6852FF8251CEF381

if [ $BUTTON = wps ]; then
  if [ $ACTION = pressed ]; then
    lua -e "print(os.time())" > /tmp/button_press_time
  fi    
  if [ $ACTION = released ]; then
     presstime=`cat /tmp/button_press_time`
     buttondowntime=`lua -e "print(os.time()-"${presstime}")"`
     echo $buttondowntime > /tmp/button_down_time
     if [ $buttondowntime -lt 5 ]; then
       if [ -e /dos/serval.up ]; then
          /serval/upgrade /dos/serval.up
       else
          if [ -e /dos/SERVAL.up ]; then 
            /serval/upgrade /dos/SERVAL.UP
          else
            # see if there is an updated version of servald from rhizome
            /serval/servald rhizome extract file ${bundleid} /dos/serval.up
            if [ -e /dos/serval.up ]; then
               /serval/upgrade /dos/serval.up
            fi          
          fi
       fi 
     else
       # long press = factory reset
       /serval/upgrade /serval/serval.factory
     fi
     /serval/servald stop ; /serval/servald start
  fi
fi

